### ISSUE TITLE
Add Section

### ISSUE THREAD

**Issue by aatayde** [aatayde/aatayde.github.io#13]
@aatayde Please create an about me section above skills.

**Comment by emergenitro** [comment]
May I take this up?

**Comment by aatayde** [comment]
Sorry.
I've assigned this issue to myself  as motivation to continue developing my portfolio page.
Thank you for your interest, I will consider it in future projects.

**Comment by aatayde** [comment]
About section has been added with some information about myself in commit e102f04.
Issue is resolved.
